/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./components/Footer.vue')['default']
    IconsIconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconsIconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconsIconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconsIconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconsIconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    ItemList: typeof import('./components/ItemList.vue')['default']
    List: typeof import('./components/List.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    ModalDialog: typeof import('./components/ModalDialog.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    NavigationBar: typeof import('./components/NavigationBar.vue')['default']
    PageFooter: typeof import('./components/PageFooter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
